version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "/auction"

  mongodb:
    image: mongo:latest
    container_name: go_mongo
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env